name = "interpreter"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Interpreter"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "assertCmd"
scope = "pnwamk"
git = "https://github.com/pnwamk/lean4-assert-command"

[[lean_lib]]
name = "Interpreter"

[[lean_exe]]
name = "interpreter"
root = "Main"
