name = "interpreter"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Interpreter"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "Paperproof"
git = "https://github.com/Paper-Proof/paperproof.git"
subDir = "lean"
rev = "main"

[[require]]
name = "assertCmd"
scope = "pnwamk"
git = "https://github.com/pnwamk/lean4-assert-command"

[[require]]
name = "all"
git = "https://www.github.com/yonatan-reicher/lean-all.git"
rev = "main"

[[lean_lib]]
name = "Interpreter"

[[lean_exe]]
name = "interpreter"
root = "Main"
